name: "Push workflow"
description: "Push workflow in remote or local repository"
author: "Vinayak Jadhav"

inputs:
  name:
    description: "Name"
    required: true
    default: "Hello"

runs:
  using: "docker"
  image: 'Dockerfile'
  args:
    - ${{ inputs.name }}

branding:
  icon: "check-square"
  color: "white"