name: Build

on: 
  workflow_dispatch:
  push:


jobs:
  Build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: ./
      with:
        gh-token: ${{ secrets.PAT_TOKEN }}
        Environment-Name: 'dev'
        Filespath: ${{ github.workspace}}/files
        FileName: '.json'

    - run: |
        get-childitem env:
      shell: pwsh